on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy to n2021.classroom.in.net
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd /usr/share/nginx/n2021e/html && git pull origin main'
          exit
