on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy to n2021.classroom.in.net
    runs-on: ubuntu-latest
    steps:
      - run: curl https://n2021.classroom.in.net
      - run: shutdown -h now
